input-datastore:
  Cluster:
    type: "Mongo"
    config:
      datastore-name: "Cluster-Test"
      collection-name: "LabelPropClusters-David"
      location: "mongodb://localhost:27017"

  WordFrequency:
    type: "Mongo"
    config:
      datastore-name: "WordFrequency-David"
      collection-name: "RelativeUserWordFrequency"
      location: "mongodb://localhost:27017"

output-datastore:
  TopWords:
    type: "Mongo"
    config:
      datastore-name: "Cluster-Test"
      collection-name: "LabelPropClusters-David-Topwords"
      location: "mongodb://localhost:27017"