input-datastore:
    Download-Source:
        type: "JSON"
        config: ~
output-datastore:
    RawTweets:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "JSONData"
            collection-name: "RawTweets"