input-datastores:
  input-ds1:
    project-type: "Download"
    datastore-name: "TweepyClient"
    collection-name: "TweepyClient"
    type: "Tweepy"
    location: ""
  
output-datastores:
  output-ds1:
    project-type: "Download"
    datastore-name: "TwitterTweetDownload"
    collection-name: "getTweetsByTimeframeUser"
    type: "MongoDB"
    location: "mongodb://localhost:27017"

  output-ds2:
    project-type: "Download"
    datastore-name: "TwitterTweetDownload"
    collection-name: "getTweetsByUser"
    type: "MongoDB"
    location: "mongodb://localhost:27017"

  output-ds3:
    project-type: "Download"
    datastore-name: "TwitterFriendsDownload"
    collection-name: "getFriendsByScreenName"
    type: "MongoDB"
    location: "mongodb://localhost:27017"

  output-ds4:
    project-type: "Download"
    datastore-name: "TwitterFriendsDownload"
    collection-name: "getFriendsByID"
    type: "MongoDB"
    location: "mongodb://localhost:27017"

  output-ds5:
    project-type: "Download"
    datastore-name: "TwitterFollowingDownload"
    collection-name: "getFollowingByScreenName"
    type: "MongoDB"
    location: "mongodb://localhost:27017"
  
  