input-datastore:
    Download-Source:
        type: "Tweepy"
        config: ~
inout-datastore:
    Users:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Users"
    UserTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserTweets"
    Friends:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Friends"
    Community:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Community"
    CleanedFriends:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "CleanedFriends"
    Cluster:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Cluster"
    Ranking:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "Ranking"

