input-datastore:
    Download-Source:
        type: "Tweepy"
        config: ~
    LocalNeighbourhoods:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "LocalNeighbourhoods"
inout-datastore:
    UserTweets:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserTweets"
