input-datastore:
    RawTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "RawTweet"
output-datastore:
    ProcessedTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "ProcessedTweets"
