input-datastore:
    ProcessedTweet:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "ProcessedTweets"
    UserWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserWordFrequency"
    GlobalWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "GlobalWordFrequency"
            
output-datastore:
    UserWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "UserWordFrequency"
    RelativeUserWordFrequency:
        type: "Mongo"
        config:
            location: "mongodb://localhost:27017"
            datastore-name: "Data"
            collection-name: "RelativeUserWordFrequency"


